### ISSUE TITLE
Requirements.txt 

### ISSUE THREAD

**Issue by albertotono** [AntheaLi/3DPartAssembly#2]
Installation issues

**Comment by albertotono** [comment]
Most of the error above was due to Python 3.8 most luckily, I move to Python3.6 as suggested but I got this. 

```
ERROR: Command errored out with exit status 1:
     command: /home/alberto/anaconda3/envs/3dpartassembly/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qe61d8u8/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qe61d8u8/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ty8x92u4
         cwd: /tmp/pip-install-qe61d8u8/torch-scatter/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qe61d8u8/torch-scatter/setup.py", line 3, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
```

**Comment by albertotono** [comment]
I tried to install the Pytorch version 1.3.1 

`pip install torch==1.3.1+cu100 torchvision==0.4.2+cu100 -f https://download.pytorch.org/whl/torch_stable.htm`

https://github.com/rusty1s/pytorch_geometric/issues/936

Still issues installing Pytorch 1.3.1, I think it should be installed with torchvision==0.4.2 right?

**Comment by albertotono** [comment]
installing python 3.6 and then running that code solved it.
