### ISSUE TITLE
RuntimeError: Expected one of cpu, cuda, mkldnn, opengl, opencl, ideep, hip, msnpu device type at start of device string: 0

### ISSUE THREAD

**Issue by albertotono** [AntheaLi/3DPartAssembly#8]
When I run the training I get this. 

```
train.sh
./train.py --exp_suffix exp_segmentation --category Table-mixed --device 0 --model_version model --num_epoch_every_visu 1 --num_batch_every_visu 1 --epochs 100000 --overwrite --data_dir /home/alberto/Documents/3DPartAssembly/exps/utils/cd/assembly_data/data --lr_decay_every 5000

Random Seed: 8164
Traceback (most recent call last):
  File "./train.py", line 405, in <module>
    device = torch.device(conf.device)
RuntimeError: Expected one of cpu, cuda, mkldnn, opengl, opencl, ideep, hip, msnpu device type at start of device string: 0
```

**Comment by albertotono** [comment]
ok I changed the device = cuda.

I got this 

```

/orion/u/liyichen/assembly/assembly/assembly/stats/train_test_splits/Table-mixed-train.txt
Traceback (most recent call last):
  File "./train.py", line 414, in <module>
    train(conf)
  File "./train.py", line 28, in train
    max_num_mask = conf.max_num_parts, max_num_similar_parts=conf.max_num_similar_parts, img_size=conf.img_size, on_kaichun_machine=conf.on_kaichun_machine)
  File "/home/alberto/Documents/3DPartAssembly/exps/exp_segmentation/data.py", line 42, in __init__
    with open(self.data_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/orion/u/liyichen/assembly/assembly/assembly/stats/train_test_splits/Table-mixed-train.txt'

```
