### ISSUE TITLE
/orion/u/liyichen/  vs /orion/u/kaichun

### ISSUE THREAD

**Issue by albertotono** [AntheaLi/3DPartAssembly#9]
When I extract the data they are from this folder path. 

`3DPartAssembly/exps/utils/cd/assembly_data/data/Table-mixed/orion/u/kaichun`

should I change the file path?

```
/orion/u/liyichen/assembly/assembly/assembly/stats/train_test_splits/Table-mixed-train.txt
Traceback (most recent call last):
  File "./train.py", line 414, in <module>
    train(conf)
  File "./train.py", line 28, in train
    max_num_mask = conf.max_num_parts, max_num_similar_parts=conf.max_num_similar_parts, img_size=conf.img_size, on_kaichun_machine=conf.on_kaichun_machine)
  File "/home/alberto/Documents/3DPartAssembly/exps/exp_segmentation/data.py", line 42, in __init__
    with open(self.data_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/orion/u/liyichen/assembly/assembly/assembly/sta
```

**Comment by albertotono** [comment]
the train_test_split?
I think that is what is [missing]( https://github.com/AntheaLi/3DPartAssembly/blob/5215ef58f740a4cd3556dd6361f00b7221a81ce4/exps/exp_segmentation/data.py#L32)

**Comment by AntheaLi** [comment]
change it to the stats folder in the repo
